In [ ]:
from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.orm import declarative_base, sessionmaker

engine = create_engine("sqlite:///my_database.db", echo=True)
Base = declarative_base()
Session = sessionmaker(bind=engine)
session = Session()

In [ ]:
# User Table
class User(Base):
    __tablename__ = 'users'
    user_id = Column(Integer, primary_key=True)
    name = Column(String)
    age = Column(Integer)

# Product Table
class Product(Base):
    __tablename__ = 'products'
    product_id = Column(Integer, primary_key=True)
    name = Column(String)
    producer = Column(String)

In [ ]:
# creating tables
Base.metadata.create_all(engine)

2025-07-25 17:52:26,464 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-25 17:52:26,470 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("users")
2025-07-25 17:52:26,470 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-07-25 17:52:26,475 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("users")
2025-07-25 17:52:26,475 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-07-25 17:52:26,478 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("products")
2025-07-25 17:52:26,479 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-07-25 17:52:26,479 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("products")
2025-07-25 17:52:26,482 INFO sqlalchemy.engine.Engine [raw sql] ()
2025-07-25 17:52:26,485 INFO sqlalchemy.engine.Engine
CREATE TABLE users (
	user_id INTEGER NOT NULL,
	name VARCHAR,
	age INTEGER,
	PRIMARY KEY (user_id)
)


2025-07-25 17:52:26,487 INFO sqlalchemy.engine.Engine [no key 0.00129s] ()
2025-07-25 17:52:26,494 INFO sqlalchemy.engine.Engine
CREATE TABLE products (
	product_id INTEGER NOT NULL,
	name VARCHAR,
	producer VARCHAR,
	PRIMARY KEY (product_id)
)


2025-07-25 17:52:26,497 INFO sqlalchemy.engine.Engine [no key 0.00221s] ()
2025-07-25 17:52:26,507 INFO sqlalchemy.engine.Engine COMMIT

In [ ]:
# adding records in Users
u1 = User(name="Kuldeep", age=20)
u2 = User(name="Vedant", age=19)

# adding records in Products
p1 = Product(name="iPhone", producer="Apple")
p2 = Product(name="Galaxy", producer="Samsung")

# Add to session and commit
session.add_all([u1, u2, p1, p2])
session.commit()

2025-07-25 17:53:19,412 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-25 17:53:19,415 INFO sqlalchemy.engine.Engine INSERT INTO products (name, producer) VALUES (?, ?) RETURNING product_id
2025-07-25 17:53:19,415 INFO sqlalchemy.engine.Engine [generated in 0.00017s (insertmanyvalues) 1/2 (ordered; batch not supported)] ('iPhone', 'Apple')
2025-07-25 17:53:19,424 INFO sqlalchemy.engine.Engine INSERT INTO products (name, producer) VALUES (?, ?) RETURNING product_id
2025-07-25 17:53:19,424 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/2 (ordered; batch not supported)] ('Galaxy', 'Samsung')
2025-07-25 17:53:19,430 INFO sqlalchemy.engine.Engine INSERT INTO users (name, age) VALUES (?, ?) RETURNING user_id
2025-07-25 17:53:19,432 INFO sqlalchemy.engine.Engine [generated in 0.00021s (insertmanyvalues) 1/2 (ordered; batch not supported)] ('Kuldeep', 20)
2025-07-25 17:53:19,432 INFO sqlalchemy.engine.Engine INSERT INTO users (name, age) VALUES (?, ?) RETURNING user_id
2025-07-25 17:53:19,432 INFO sqlalchemy.engine.Engine [insertmanyvalues 2/2 (ordered; batch not supported)] ('Vedant', 19)
2025-07-25 17:53:19,432 INFO sqlalchemy.engine.Engine COMMIT

In [ ]:
# Fetch all users
users = session.query(User).all()
for user in users:
    print(f"{user.user_id}: {user.name} ({user.age})")

# Fetch all products
products = session.query(Product).all()
for product in products:
    print(f"{product.product_id}: {product.name} by {product.producer}")

2025-07-25 17:53:37,054 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-25 17:53:37,057 INFO sqlalchemy.engine.Engine SELECT users.user_id AS users_user_id, users.name AS users_name, users.age AS users_age
FROM users
2025-07-25 17:53:37,057 INFO sqlalchemy.engine.Engine [generated in 0.00130s] ()
1: Kuldeep (20)
2: Vedant (19)
2025-07-25 17:53:37,062 INFO sqlalchemy.engine.Engine SELECT products.product_id AS products_product_id, products.name AS products_name, products.producer AS products_producer
FROM products
2025-07-25 17:53:37,062 INFO sqlalchemy.engine.Engine [generated in 0.00123s] ()
1: iPhone by Apple
2: Galaxy by Samsung

In [ ]:
# Update user name
user = session.query(User).filter_by(name="Vedant").first()
user.name = "Ved"
session.commit()

2025-07-25 17:55:02,032 INFO sqlalchemy.engine.Engine SELECT users.user_id AS users_user_id, users.name AS users_name, users.age AS users_age
FROM users
WHERE users.name = ?
 LIMIT ? OFFSET ?
2025-07-25 17:55:02,032 INFO sqlalchemy.engine.Engine [generated in 0.00174s] ('Vedant', 1, 0)
2025-07-25 17:55:02,035 INFO sqlalchemy.engine.Engine UPDATE users SET name=? WHERE users.user_id = ?
2025-07-25 17:55:02,035 INFO sqlalchemy.engine.Engine [generated in 0.00173s] ('Ved', 2)
2025-07-25 17:55:02,042 INFO sqlalchemy.engine.Engine COMMIT

In [ ]:
# Delete a product
product_to_delete = session.query(Product).filter_by(name="Galaxy").first()
session.delete(product_to_delete)
session.commit()

2025-07-25 17:55:18,195 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-25 17:55:18,196 INFO sqlalchemy.engine.Engine SELECT products.product_id AS products_product_id, products.name AS products_name, products.producer AS products_producer
FROM products
WHERE products.name = ?
 LIMIT ? OFFSET ?
2025-07-25 17:55:18,198 INFO sqlalchemy.engine.Engine [generated in 0.00131s] ('Galaxy', 1, 0)
2025-07-25 17:55:18,202 INFO sqlalchemy.engine.Engine DELETE FROM products WHERE products.product_id = ?
2025-07-25 17:55:18,204 INFO sqlalchemy.engine.Engine [generated in 0.00148s] (2,)
2025-07-25 17:55:18,206 INFO sqlalchemy.engine.Engine COMMIT

In [ ]:
# Fetch all users
users = session.query(User).all()
for user in users:
    print(f"{user.user_id}: {user.name} ({user.age})")

# Fetch all products
products = session.query(Product).all()
for product in products:
    print(f"{product.product_id}: {product.name} by {product.producer}")

2025-07-25 17:56:38,033 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-07-25 17:56:38,035 INFO sqlalchemy.engine.Engine SELECT users.user_id AS users_user_id, users.name AS users_name, users.age AS users_age
FROM users
2025-07-25 17:56:38,037 INFO sqlalchemy.engine.Engine [cached since 181s ago] ()
1: Kuldeep (20)
2: Ved (19)
2025-07-25 17:56:38,037 INFO sqlalchemy.engine.Engine SELECT products.product_id AS products_product_id, products.name AS products_name, products.producer AS products_producer
FROM products
2025-07-25 17:56:38,037 INFO sqlalchemy.engine.Engine [cached since 181s ago] ()
1: iPhone by Apple